# Generated by Django 5.0.2 on 2024-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='commune',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
