# Generated by Django 5.0.2 on 2024-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_state_shippingaddress_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='product',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
