# Generated by Django 5.0.2 on 2024-06-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='payment',
        ),
    ]
