# Generated by Django 5.0.2 on 2024-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_shippingaddress_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
