# Generated by Django 5.0.2 on 2024-06-14 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_shippingaddress_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Ordered',
        ),
    ]
