# Generated by Django 5.0.2 on 2024-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_shippingaddress_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='ordered',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
