# Generated by Django 5.0.2 on 2024-06-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_order_complete_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='complete',
        ),
    ]
