# Generated by Django 4.1.7 on 2024-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_revenue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revenue',
            new_name='Statistic',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
