# Generated by Django 4.1.7 on 2024-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_revenue_statistic_customer_date_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
